# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/esperimenti/ignite/projects/test board/firmware/uart/uart.srcs/sources_1/ip/clock_wizard/clock_wizard.xci
# IP: The module: 'clock_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/clock_wizard/clock_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/clock_wizard/clock_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/clock_wizard/clock_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/esperimenti/ignite/projects/test board/firmware/uart/uart.srcs/sources_1/ip/clock_wizard/clock_wizard.xci
# IP: The module: 'clock_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/clock_wizard/clock_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/clock_wizard/clock_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/clock_wizard/clock_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
