serial:
  port: "COM3"
  baud: 115200

injection:
  bypass: 0
  period: 63
  burst: 1
  duty: 8

tasks:

  - name: TEST_TUNING_0
    operation: matrix_scan
    sweep:
      start_v: 100
      end_v: 20
      step_v: 5
      num_injections: 10
      pixel_x: 0
      pixel_y: 0
    config:
      dac_th: 0
      cap25: 0
      cap50: 0
      test_en: 1
      cap_csa_load: 1
      t_up: 0
      out_en: 1
      x: 0
      y: 0
    tuner:
      file: tuner_configs/tdac_tuning_results.tsv
    
  - name: TEST_TUNING_cap50
    operation: matrix_scan
    sweep:
      start_v: 100
      end_v: 20
      step_v: 5
      num_injections: 10
      pixel_x: 0
      pixel_y: 0
    config:
      dac_th: 0
      cap25: 0
      cap50: 1
      test_en: 1
      cap_csa_load: 1
      t_up: 0
      out_en: 1
      x: 0
      y: 0
    tuner:
      file: tuner_configs/tdac_tuning_results.tsv

  - name: TEST_TUNING_cap25
    operation: matrix_scan
    sweep:
      start_v: 100
      end_v: 20
      step_v: 5
      num_injections: 10
      pixel_x: 0
      pixel_y: 0
    config:
      dac_th: 0
      cap25: 1
      cap50: 0
      test_en: 1
      cap_csa_load: 1
      t_up: 0
      out_en: 1
      x: 0
      y: 0
    tuner:
      file: tuner_configs/tdac_tuning_results.tsv

  - name: TEST_TUNING_cap75
    operation: matrix_scan
    sweep:
      start_v: 100
      end_v: 20
      step_v: 5
      num_injections: 10
      pixel_x: 0
      pixel_y: 0
    config:
      dac_th: 0
      cap25: 1
      cap50: 1
      test_en: 1
      cap_csa_load: 1
      t_up: 0
      out_en: 1
      x: 0
      y: 0
    tuner:
      file: tuner_configs/tdac_tuning_results.tsv

