# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.srcs/sources_1/ip/spi_fifo/spi_fifo.xci
# IP: The module: 'spi_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/spi_fifo/spi_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/spi_fifo/spi_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/spi_fifo/spi_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.srcs/sources_1/ip/spi_fifo/spi_fifo.xci
# IP: The module: 'spi_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/spi_fifo/spi_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/spi_fifo/spi_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/esperimenti/ignite/projects/test board/firmware/uart/uart.gen/sources_1/ip/spi_fifo/spi_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
