# Definizione del blocco CONFIG comune
common_config: &DEFAULT_CONFIG # <--- ANCORA definita con &
  cap25: 0
  cap50: 1
  test_en: 1
  cap_csa_load: 1
  out_en: 1
  x: 0
  y: 0
# ---

# Definizione del blocco SWEEP comune (ad eccezione dei valori start/end)
common_sweep_params: &DEFAULT_SWEEP
  step_v: 3
  num_injections: 31
  pixel_x: 0
  pixel_y: 0
# ---

serial:
  port: "COM3"
  baud: 115200

injection:
  bypass: 0
  period: 63
  burst: 1
  duty: 8

tasks:
  # Task 1: TUP_0__DAC_0
  - name: TUP_0__DAC_0
    operation: matrix_scan
    sweep:
      start_v: 90
      end_v: 30
      <<: *DEFAULT_SWEEP # <--- ALIAS che include i parametri comuni
    config:
      dac_th: 0
      t_up: 0
      <<: *DEFAULT_CONFIG # <--- ALIAS che include la configurazione comune
      
  # Task 2: TUP_0__DAC_8
  - name: TUP_0__DAC_8
    operation: matrix_scan
    sweep:
      start_v: 80
      end_v: 25
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 8
      t_up: 0
      <<: *DEFAULT_CONFIG

  # Task 3: TUP_0__DAC_16
  - name: TUP_0__DAC_16
    operation: matrix_scan
    sweep:
      start_v: 75
      end_v: 25
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 16
      t_up: 0
      <<: *DEFAULT_CONFIG
  # Task 4: TUP_0__DAC_24
  - name: TUP_0__DAC_24
    operation: matrix_scan
    sweep:
      start_v: 65
      end_v: 20
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 24
      t_up: 0
      <<: *DEFAULT_CONFIG

  # Task 5: TUP_0__DAC_31
  - name: TUP_0__DAC_31
    operation: matrix_scan
    sweep:
      start_v: 55
      end_v: 10
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 31
      t_up: 0
      <<: *DEFAULT_CONFIG


      
  # Task 6: TUP_1__DAC_0
  - name: TUP_1__DAC_0
    operation: matrix_scan
    sweep:
      start_v: 80
      end_v: 30
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 0
      t_up: 1
      <<: *DEFAULT_CONFIG
      
  # Task 7: TUP_1__DAC_8
  - name: TUP_1__DAC_8
    operation: matrix_scan
    sweep:
      start_v: 90
      end_v: 30
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 8
      t_up: 1
      <<: *DEFAULT_CONFIG

  # Task 8: TUP_1__DAC_16
  - name: TUP_1__DAC_16
    operation: matrix_scan
    sweep:
      start_v: 100
      end_v: 40
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 16
      t_up: 1
      <<: *DEFAULT_CONFIG

  # Task 9: TUP_1__DAC_24
  - name: TUP_1__DAC_24
    operation: matrix_scan
    sweep:
      start_v: 110
      end_v: 45
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 24
      t_up: 1
      <<: *DEFAULT_CONFIG

  # Task 10: TUP_1__DAC_31
  - name: TUP_1__DAC_31
    operation: matrix_scan
    sweep:
      start_v: 120
      end_v: 50
      <<: *DEFAULT_SWEEP
    config:
      dac_th: 31
      t_up: 1
      <<: *DEFAULT_CONFIG