serial:
  port: "COM3"
  baud: 115200

injection:
  bypass: 0
  period: 63
  burst: 1
  duty: 8

tasks:
  - name: sweep_pixel_10_10
    operation: sweep_pixel

    sweep:
      start_v: 100
      end_v: 30
      step_v: 3
      num_injections: 31
      pixel_x: 10
      pixel_y: 6
    config:
      dac_th: 12
      cap25: 1
      cap50: 0
      test_en: 1
      cap_csa_load: 1
      t_up: 0
      out_en: 1
      x: 10
      y: 6


    